image: python:3.5

before_script:
  - pip install tox setuptools
cache:
  paths:
  - /root/.cache
stages:
  - style
  - test
  - package

py35:
  stage: test
  script:
    - tox -e py35

flake8:
  stage: style
  script:
    - tox -e flake8

wheel:
  stage: package
  script:
    tox -e wheel
  artifacts:
    paths:
      - dist/

sdist:
  stage: package
  script:
    tox -e sdist
  artifacts:
    paths:
      - dist/
